defaults:
- model: wav2vec2
- opt: adam
- scheduler: id_scheduler
- train_ds:
  - ssp_net_vc
- val_ds:
  - ssp_net_vc
- _self_

hydra:
  run:
    dir: '.'

checkpoint_dir: "checkpoints/${wandb_group}"
checkpoint_freq: 1
num_epochs: ???
num_workers: 8
seed: 8228
train_batch_size: 16
val_batch_size: 16
wandb_file_name: null
wandb_group: ???
wandb_log_freq: 100
wandb_run_path: null
