defaults:
- model: wav2vec2
- opt: adam
- train_ds:
  - ssp_net_vc
- val_ds:
  - ssp_net_vc
- _self_

hydra:
  run:
    dir: '.'

batch_size: 16
checkpoint_dir: "checkpoints/${wandb_group}"
checkpoint_freq: 1
num_epochs: ???
seed: 8228
wandb_file_name: null
wandb_group: ???
wandb_log_freq: 100
wandb_run_path: null
